project_id = "omazcdcyqrdvyyxzvmyx"

[functions.parse-cv]
verify_jwt = false

[functions.scrape-job]
verify_jwt = false

[functions.ai-tailor]
verify_jwt = false

[functions.cv-review]
verify_jwt = true

[functions.ai-prescreen]
verify_jwt = false